name: Benchmark
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: write
  pull-requests: write
  actions: write
jobs:
  run_benchmarks:
    if: "!contains(github.event.head_commit.message, '[skip-manual-bench]')"
    name: Benchmark (${{ matrix.branch }}-S${{ matrix.order }}N${{ matrix.nested }}M${{ matrix.multi }}C${{ matrix.compression }}R${{ matrix.runs }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Doesn't fail everything if something fails
      matrix:
        branch: ["OPTIMIZED", "MAIN"]
        order: ["15", "66", "77"]
        compression: ["A"]
        multi: ["1", "0"]
        nested: ["1", "0"]
        runs: ["1000"]
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_MAXSIZE: 8G
      CCACHE_COMPRESS: "true"
      GH_TOKEN: ${{ github.token }}
      # head_ref is the branch name on Pull Requests.
      # ref_name is the branch name on direct pushes.
      CACHE_BRANCH: ${{ github.head_ref || github.ref_name }}
      CONFIG: S${{ matrix.order }}N${{ matrix.nested }}M${{ matrix.multi }}C${{ matrix.compression }}R${{ matrix.runs }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # Explicitly checkout the branch so we can push commits back to it
          ref: ${{ github.head_ref || github.ref_name }}
      - name: System setup
        run: |
          # Update packages
          sudo apt-get update
          # Required packages
          sudo apt-get install -y ccache ninja-build libsnappy-dev libbenchmark-dev vmtouch golang
      - name: Restore and Clean cache
        uses: ./.github/actions/manage-cache
        with:
          cache_branch: ${{ env.CACHE_BRANCH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run the golang automated runner
        run: |
          cd runner
          sudo bash -c "ulimit -l \$(grep MemTotal /proc/meminfo | awk '{print \$2}') && export PYARROW_OPENASTRONOMY_BENCHMARK_BRANCH=${{ matrix.branch }} && export PYARROW_OPENASTRONOMY_BENCHMARK=S${{ matrix.order }}N${{ matrix.nested }}M${{ matrix.multi }}C${{ matrix.compression }}R${{ matrix.runs }} && go run ."
      - name: Upload database artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-artifact-${{ matrix.branch }}-S${{ matrix.order }}N${{ matrix.nested }}M${{ matrix.multi }}C${{ matrix.compression }}R${{ matrix.runs }}          
          path: "**/*.db"
          retention-days: 1
  commit-results:
    if: "!contains(github.event.head_commit.message, '[skip-manual-bench]')"
    name: Commit all databases
    needs: run_benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Download all DB artifacts
        uses: actions/download-artifact@v4
        with:
          path: benchmark_results/
          merge-multiple: true
      - name: Commit and push database files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add "**/*.db"
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: auto-update benchmark database [skip ci]"
            git push
          else
            echo "No database changes detected. Skipping commit."
          fi
