name: Build and Benchmark
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  pull-requests: write
  actions: write # Required: 'gh cache delete'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_MAXSIZE: 8G
      CCACHE_COMPRESS: "true"
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout benchmark repository
        uses: actions/checkout@v4

      - name: Checkout Arrow fork
        uses: actions/checkout@v4
        with:
          repository: 'OmBiradar/arrow'
          path: 'arrow-src'
          filter: 'blob:none' 

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache ninja-build

      - name: ccache Storage
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ${{ runner.os }}-arrow-ccache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-arrow-ccache-

      - name: Purge old cache
        run: |
          echo "Cleaning up old caches..."
          gh cache list --key "${{ runner.os }}-arrow-ccache-" --json id -q '.[].id' \
          | xargs -I{} gh cache delete {} || echo "Locker is already empty."

      - name: Execute build script
        run: |
          export PATH="/usr/lib/ccache:$PATH"
          chmod +x ./build.sh
          
          echo "Starting build..."
          START_TIME=$(date +%s)
          
          ./build.sh
          
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          MINUTES=$((DURATION / 60))
          SECONDS=$((DURATION % 60))
          BUILD_TIME="${MINUTES}m ${SECONDS}s"
          
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV
          
          echo "### 🚀 Build Metrics" >> $GITHUB_STEP_SUMMARY
          echo "- **Time to compile:** $BUILD_TIME" >> $GITHUB_STEP_SUMMARY

      - name: Comment Build Time on PR
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "🚀 **Build Completed!**
            ⏱️ **Build Time:** ${{ env.BUILD_TIME }}
            _Commit: ${{ github.sha }}_"